project:
  type: website

website:
  title: "MOVER datasets overview"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - demographics.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    page-layout: full

execute: 
  warning: false

